---
version: '3'
services:
  docker-daemon:
    container_name: "dind-server"
    environment:
      DOCKER_TLS_CERTDIR: ""
    image: "docker:dind"
    privileged: true
  jenkins:
    container_name: jenkins
    depends_on:
      - "docker-daemon"
    environment:
      DOCKER_HOST: "tcp://docker:2375"
    restart: always
    build:
        context: jenkins-server
    image: jenkins-server
    ports:
      - "8081:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
