---
version: '3'
services:
  jenkins:
    container_name: jenkins
    restart: always
    build:
        context: jenkins-ansible
    image: jenkins-ansible
    ports:
      - "8081:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
